services:
  vp-docker:
    image: xieruan/vp:dev
    container_name: vp
    restart: always
    ports:
      - "服务端口:服务端口"
    volumes:
      - /root/.cert:/root/.cert
    environment:
      URL: "https://xxx.com"
      TOKEN: "通信密匙"
      NODEID: "节点id"
      LOCALPORT: "监听端口"
      CHECKRATE: 60
      LOGLEVEL: "info"
    logging:
      driver: "json-file"
      options:
        max-size: 500m
